### ISSUE TITLE
Migration > Cannot recompute the consumptions of Transaction ID '532472417' in Tenant 'SAP Labs France - Charge@Home' ('slfcah')

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1739]
```
[
      {
            "error": "Cannot read property 'id' of null",
            "stack": "TypeError: Cannot read property 'id' of null
   at Function.addSiteLimitationToConsumption (/Users/I339261/Sources/ev-server-git/dist/webpack:/src/utils/Utils.ts:1800:128)
   at Function.createConsumptionFromMeterValue (/Users/I339261/Sources/ev-server-git/dist/webpack:/src/server/ocpp/utils/OCPPUtils.ts:767:9)
   at Function.createConsumptionsFromMeterValues (/Users/I339261/Sources/ev-server-git/dist/webpack:/src/server/ocpp/utils/OCPPUtils.ts:604:42)
   at Function.rebuildTransactionConsumptions (/Users/I339261/Sources/ev-server-git/dist/webpack:/src/server/ocpp/utils/OCPPUtils.ts:369:22)
   at bluebird_1.default.map.concurrency (/Users/I339261/Sources/ev-server-git/dist/webpack:/src/migration/tasks/RecomputeAllTransactionsConsumptionsTask.ts:56:37)"
      }
]
```

**Comment by LucasBrazi06** [comment]
Fixed in 3b9fbc0e9d6c878a974f16bfdbbf22934b200f42
